baseURL = "https://watsonism.github.io/"
languageCode = "en-us"
title = "w a t s o n"
# theme = "onyx"
[module]
  [[module.imports]]
    path = "github.com/kaushalmodi/hugo-onyx-theme"
  [[module.imports]]
    path = "github.com/kaushalmodi/hugo-debugprint"

[markup]
  [markup.highlight]
    codeFences = true # default = true
    noClasses = false # default = true

  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true # This is *necessary* for ox-hugo to work well with Hugo 0.60.0+

[caches]
  [caches.getjson]
    dir = ":cacheDir/:project"
    maxAge = "1m" # Disable caching getJSON data

[Permalinks]
  # post = "/:year/:month/:title/"
  # Below, we have
  #   foo = "bar"
  # where foo = section name without double quotes for which we want to have
  # the custom permalinks. If foo is 'posts', it will apply to content in
  # content/posts/ dir. The "bar" portion is how you want the links to look.
  # https://gohugo.io/content-management/urls/#permalink-configuration-values
  doc = "/doc/:filename/"
  test = "/test/:slug/"

[Params]
  name = "ox-hugo"
  description = "Org mode to Hugo exporter<br />Write your Hugo posts in native Org mode."

  # Go date formats: https://golang.org/pkg/time/#pkg-constants
  dateform = "Mon Jan 2, 2006"

  github_user = "watsonism"
  github_repo = "blog"
  #github_workflow_file = "test.yml"
  #github_banner = true

  #images = ["/favicon-196x196.png"] # Used in twitter_cards.html partial

  custom_css = [ # Chroma Trac theme
                 # "css/trac_chroma.css" # Needs markup.highlight.noClasses to be false
                 # Chroma GitHub theme
                 "css/github_chroma.css" # Needs markup.highlight.noClasses to be false
                 , "css/style.css"
               ]
  custom_css_absolute = [ # Iosevka fonts
                          "https://cdn.jsdelivr.net/gh/kaushalmodi/iosevka-mirror@v1.14.5/iosevka.css"
                        ]
  custom_js  = []

 [Params.source]
    url = "https://github.com/watsonism/blog"
    default_branch = "main"
    org_dir = "doc"
    org_file = "index.org"

 #  [Params.sidebar]
 #    logo = "favicon.ico"

 #    github_button  = true
 #    gha_button  = true
 #    codecov_button = false
 #    gratipay = ""

 #    # Mon Sep 04 23:55:36 EDT 2017 - kmodi
 #    # Disable this option for now.. but seems to be useful in future
 #    show_relations = false

 #  [Params.footer]
 #    copyright = ""
 #    show_powered_by = true
